name: test-environment
channels:
- defaults
- conda-forge
- cantera
- cartemic
dependencies:
  - numpy>=1.12.0
  - pytest>=3.2.0
  - pytest-cov
  - pint>=0.7.2
  - pandas
  - cantera
  - mock
  - codecov
  - scipy
